### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for './test.txt' in undefined

### ISSUE THREAD

**Issue by yelloxing** [etcpack/etcpack#1]
```js
module.exports = {

    // 打包入口
    entry: './src/main.js',

    // 打包出口
    output: 'build/main.js',

    // redirect: {},

    loader: [{
        test: /\.txt$/,
        handler: ['../src/index.js']
    }]
};
```

报错：

```js
Crafted in China By hai2007, powered by EtcPack.
-------------------------------------------------------------------------
( https://etcpack.github.io/api/ )


Independent bundle file currently analyzed:
    ● /Users/kapok/hai2007/etcpack/plain-loader/test/src/main.js → /Users/kapok/hai2007/etcpack/plain-loader/test/build/main.js

    * [0] /Users/kapok/hai2007/etcpack/plain-loader/test/src/main.js
/Users/kapok/hai2007/etcpack/plain-loader/test/node_modules/etcpack/bin/build/analyseImport.js:28
    if (url in config.redirect) {
            ^

TypeError: Cannot use 'in' operator to search for './test.txt' in undefined
    at module.exports (/Users/kapok/hai2007/etcpack/plain-loader/test/node_modules/etcpack/bin/build/analyseImport.js:28:13)
    at analyseBundle (/Users/kapok/hai2007/etcpack/plain-loader/test/node_modules/etcpack/bin/build/analyseBundle.js:57:28)
    at Object.<anonymous> (/Users/kapok/hai2007/etcpack/plain-loader/test/node_modules/etcpack/bin/builder:57:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@ build: `etcpack_pkg --config etcpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by hai2007** [comment]
0.1.1开始已经修复此问题
